<?php

/**
 *
 * @file
 * Primary module hooks for fast_models module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function fast_models_theme() {
  // pre-formatage et template pour le menu.
  $hooks['layoutmenu_fast_models_fn_first_menu'] = [
    'render element' => 'element',
    'preprocess functions' => [
      'template_preprocess_layoutmenu_fast_models_fn_first_menu'
    ],
    'file' => 'fast_models.theme.inc'
  ];
 // pre-formatage et template pour le menu.
  $hooks['layoutmenu_fast_models_fn_second_menu'] = [
    'render element' => 'element',
    'preprocess functions' => [
      'template_preprocess_layoutmenu_fast_models_fn_second_menu'
    ],
    'file' => 'fast_models.theme.inc'
  ];
 
  /* formatage de la liste des head_nav */
  $hooks['layoutfield_f_news_teaser_service'] = [
    'render element' => 'element',
    'preprocess functions' => [
      'template_preprocess_layoutfield_f_news_teaser_service'
    ],
    'file' => 'fast_models.theme.inc'
  ];
  /* formatage de la liste des tag_show */
  $hooks['layoutfield_f_news_teaser_service_tag'] = [
    'render element' => 'element',
    'preprocess functions' => [
      'template_preprocess_layoutfield_f_news_teaser_service'
    ],
    'file' => 'fast_models.theme.inc'
  ];
  /* formatage de la liste des blog-btn-tag */
  $hooks['layoutfield_f_news_blog_teaser'] = [
    'render element' => 'element',
    'preprocess functions' => [
      'template_preprocess_layoutfield_f_news_teaser_service'
    ],
    'file' => 'fast_models.theme.inc'
  ];
  // hook for tag list on articles section 
  $hooks['layoutfield_f_news_article_tag'] = [
    'render element' => 'element',
    'preprocess functions' => [
      'template_preprocess_layoutfield_f_news_article_tag'
    ],
    'file' => 'fast_models.theme.inc'
  ];
  
  return $hooks;
}
