<?php

/**
 *
 * @file
 * Primary module hooks for fast_models module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function fast_models_theme() {
  // pre-formatage et template pour le menu.
  $hooks['layoutmenu_fast_models_fn_first_menu'] = [
    'render element' => 'element',
    'preprocess functions' => [
      'template_preprocess_layoutmenu_fast_models_fn_first_menu'
    ],
    'file' => 'fast_models.theme.inc'
  ];
  return $hooks;
}
